apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitpass-platform
  labels:
    app: fitpass-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitpass-platform
  template:
    metadata:
      labels:
        app: fitpass-platform
    spec:
      containers:
      - name: fitpass-platform
        image: europe-west2-docker.pkg.dev/gcp-test-470319/fitpass-platform/fitpass-platform:0.0.2
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: fitpass-redis
        - name: REDIS_PORT
          value: "6379"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: app-storage
          mountPath: /var/www
      volumes:
      - name: app-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fitpass-platform
  labels:
    app: fitpass-platform
spec:
  selector:
    app: fitpass-platform
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
