apiVersion: v1
kind: PersistentVolume
metadata:
  name: fitpass-app-storage-pv
  labels:
    app: fitpass-shared-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-rwx
  hostPath:
    path: /tmp/fitpass-app-storage
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fitpass-app-storage-claim
  labels:
    app: fitpass-shared-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwx
