apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitpass-mailhog
  labels:
    app: fitpass-mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitpass-mailhog
  template:
    metadata:
      labels:
        app: fitpass-mailhog
    spec:
      containers:
      - name: fitpass-mailhog
        image: mailhog/mailhog
        ports:
        - containerPort: 1025
          name: smtp
        - containerPort: 8025
          name: web
        livenessProbe:
          tcpSocket:
            port: 8025
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8025
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: fitpass-mailhog
  labels:
    app: fitpass-mailhog
spec:
  selector:
    app: fitpass-mailhog
  ports:
  - port: 1025
    targetPort: 1025
    protocol: TCP
    name: smtp
  - port: 8025
    targetPort: 8025
    protocol: TCP
    name: web
  type: ClusterIP