apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitpass-nginx
  labels:
    app: fitpass-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitpass-nginx
  template:
    metadata:
      labels:
        app: fitpass-nginx
    spec:
      containers:
      - name: fitpass-nginx
        image: europe-west2-docker.pkg.dev/gcp-test-470319/fitpass-platform/fitpass-nginx:0.0.1
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: app-storage
          mountPath: /var/www
      volumes:
      - name: app-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fitpass-nginx
  labels:
    app: fitpass-nginx
spec:
  selector:
    app: fitpass-nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
