apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitpass-redis
  labels:
    app: fitpass-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitpass-redis
  template:
    metadata:
      labels:
        app: fitpass-redis
    spec:
      containers:
      - name: fitpass-redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: fitpass-redis
  labels:
    app: fitpass-redis
spec:
  selector:
    app: fitpass-redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
