services:
  # --------------------------------------------------
  # redis:alpine
  # --------------------------------------------------
  redis:
    container_name: fitpass-redis
    image: redis:alpine
    platform: ${APP_PLATFORM}
    restart: unless-stopped
    ports:
      - "6380:6379"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      backend:
        ipv4_address: 10.0.0.1

  # --------------------------------------------------
  # php:8.3.0-fpm-alpine
  # --------------------------------------------------
  php:
    container_name: fitpass-php
    image: europe-west2-docker.pkg.dev/gcp-test-470319/fitpass-platform/fitpass-platform:0.0.1
    platform: ${APP_PLATFORM}
    restart: unless-stopped
    volumes:
      - ./../:/var/www:rw
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "php-fpm", "-t" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      backend:
        ipv4_address: 10.0.0.2

  # --------------------------------------------------
  # nginx:1.27.3-alpine3.20
  # --------------------------------------------------
  nginx:
    container_name: fitpass-nginx
    image: nginx:1.27.3-alpine3.20
    platform: ${APP_PLATFORM}
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/custom:/etc/nginx/custom:ro
      - ./nginx/logs:/var/log/nginx:rw
      - ./../:/var/www:rw
    depends_on:
      php:
        condition: service_healthy
    networks:
      backend:
        ipv4_address: 10.0.0.3

  # --------------------------------------------------
  # mailhog
  # --------------------------------------------------
  mailhog:
    container_name: fitpass-mailhog
    restart: unless-stopped
    image: mailhog/mailhog
    platform: linux/amd64 # There are no images for arm64 architecture.
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      backend:
        ipv4_address: 10.0.0.4

# --------------------------------------------------
# networks
# --------------------------------------------------
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
